local config = require('lapis.config')

config({'development', 'staging', 'production', 'test'}, {
    postgres = {
        host = os.getenv('DATABASE_HOST') or '127.0.0.1',
        port = os.getenv('DATABASE_PORT') or '5432',
        user = os.getenv('DATABASE_USERNAME') or 'cloud',
        password = os.getenv('DATABASE_PASSWORD') or 'snap-cloud-password',
        database = os.getenv('DATABASE_NAME') or 'snapcloud'
    },
    session_name = 'snapsession',

    -- Exception monitoring: leave empty to avoid forwarding errors.
    sentry_dsn = os.getenv('SENTRY_DSN'),
    -- Used to tag exceptions with the current commit or tag.
    -- Example: export RELEASE_SHA=$(git rev-parse --short HEAD)
    release_sha = os.getenv('RELEASE_SHA'),

    -- Change to the relative (or absolute) path of your disk storage
    -- directory.  Note that the user running Lapis needs to have
    -- read & write permissions to that path.
    store_path = os.getenv('PROJECT_STORAGE_PATH') or 'store',

    -- S3-compatible object storage (Cloudflare R2 in production, MinIO or
    -- similar for local dev). Leave endpoint/bucket empty to run purely off
    -- local disk. When both are configured, storage.lua operates in "hybrid"
    -- mode: writes go to R2, reads prefer R2 and fall back to disk so
    -- not-yet-migrated projects keep working during a slow backfill.
    s3 = {
        endpoint = os.getenv('S3_ENDPOINT'),
        bucket = os.getenv('S3_BUCKET'),
        access_key_id = os.getenv('S3_ACCESS_KEY_ID'),
        secret_access_key = os.getenv('S3_SECRET_ACCESS_KEY'),
        region = os.getenv('S3_REGION') or 'auto',
        -- Optional: the host URL the browser will hit for presigned GETs.
        -- Defaults to the endpoint. Use for R2 custom domains or a CDN.
        public_host = os.getenv('S3_PUBLIC_HOST'),
    },
    -- How long presigned image URLs are valid for (seconds). Short-lived
    -- because permission checks run at presign time.
    s3_presign_ttl = tonumber(os.getenv('S3_PRESIGN_TTL')) or 300,
    -- When true, hybrid-mode saves still write a local disk copy as a
    -- safety net. Set S3_DISK_WRITES=false once the backfill is complete
    -- and every save is known to be reaching S3 successfully, so new
    -- writes stop piling up on the box's local disk. Default true so
    -- rollout is safe by default.
    s3_disk_writes = (os.getenv('S3_DISK_WRITES') ~= 'false'),

    -- Shared-secret bearer token for /api/v1/admin/storage/* endpoints.
    -- Used by bin/migrate-to-r2.sh and any other out-of-band backfill
    -- runner. We deliberately do NOT require an admin cookie: the
    -- backfill is driven by a long-running shell loop and wrapping it
    -- in a session makes that brittle. Leave unset to disable the
    -- endpoints entirely (safer default than a guessable string).
    storage_migration_token = os.getenv('STORAGE_MIGRATION_TOKEN'),

    -- How many retired versions we keep in object storage per project,
    -- in addition to the live `current` files. Mirrors the legacy disk
    -- scheme's `d-1` + `d-2` => 2. Raising this costs R2 storage and
    -- per-project rows in `project_versions` but no extra S3 ops on
    -- read; retention logic in storage.lua enforces the cap by soft-
    -- deleting the oldest entries.
    previous_versions_to_keep =
        tonumber(os.getenv('PREVIOUS_VERSIONS_TO_KEEP')) or 2,
    -- A retired version older than this (seconds) is considered
    -- "stable" and will be preserved across the next save. Versions
    -- younger than this are treated as rapid-edit churn and get rotated
    -- out to avoid storing every single save. 12h matches the legacy
    -- disk scheme's d-2 threshold (43200s).
    stable_version_age_seconds =
        tonumber(os.getenv('STABLE_VERSION_AGE_SECONDS')) or 12 * 60 * 60,

    -- for sending email
    mail_user = os.getenv('MAIL_SMTP_USER') or 'cloud',
    mail_password = os.getenv('MAIL_SMTP_PASSWORD') or 'cloudemail',
    mail_server = os.getenv('MAIL_SMTP_SERVER') or '127.0.0.1',
    mail_from_name = "Snap!Cloud",
    mail_from = "noreply@snap.berkeley.edu",
    mail_footer = "<br/><br/><p><small>Please do not reply to this email. This message was automatically generated by the Snap!Cloud. To contact an actual human being, please write to <a href='mailto:contact@snap.berkeley.edu'>contact@snap.berkeley.edu</a></small></p>",

    discourse_sso_secret = os.getenv('DISCOURSE_SSO_SECRET'),
    worker_connections = os.getenv('WORKER_CONNECTIONS') or 1024,

    stat_arguments = os.getenv('STAT_ARGS') or '-c %Y',

    hostname = os.getenv('HOSTNAME') or 'localhost',
    secondary_hostname = os.getenv('SECONDARY_HOSTNAME') or 'localhost',
    maintenance_mode = os.getenv('MAINTENANCE_MODE') or 'false',

    measure_performance = true,
    logging = {
        queries = true,
        requests = true,
        server = true,
    }
})

config({'development', 'test'}, {
    use_daemon = 'off',
    site_name = 'dev | Snap Cloud',
    port = os.getenv('PORT') or 8080,
    mail_smtp_port = os.getenv('MAIL_SMTP_PORT') or 1025,
    dns_resolver = '8.8.8.8',
    code_cache = 'off',
    num_workers = 1,
    log_directive = 'stderr debug',
    secret = os.getenv('SESSION_SECRET_BASE') or 'this is a secret',

    session_name = 'snapsession_development',
    -- development needs no special SSL or cert config.
    non_ssl_nginx_config = 'locations.conf',
    -- empty string when no additional configs are included.
    ssl_nginx_server_config = ''
})

config({'test'}, {
    postgres = {
        database = 'snapcloud_test'
    },
    store_path = 'store/test',
})

config({'production', 'staging'}, {
    use_daemon = 'on',
    port = os.getenv('PORT') or 80,
    mail_smtp_port = 587,
    dns_resolver = '67.207.67.2 ipv6=off',

    secret = os.getenv('SESSION_SECRET_BASE'),
    code_cache = 'on',

    log_directive = 'logs/error.log warn',
})

config('production', {
    site_name = 'Snap Cloud',
    num_workers = 8,
    non_ssl_nginx_config = 'http-only.conf',
    ssl_nginx_server_config = 'include nginx.conf.d/ssl-production.conf;',

    -- This is an additional security feature to prevent cookie tampering.
    -- Currently disabled as changing the name will log out all users.
    -- lapis needs to /not/ URL encode this name.
    -- session_name = '__Host-snapsession',
    session_name = 'snapsession',

    logging = {
        queries = false,
        requests = true,
        server = true,
    }
})

config('staging', {
    site_name = 'staging | Snap Cloud',
    -- the staging server is a low-cpu server.
    num_workers = 2,
    non_ssl_nginx_config = 'http-only.conf',
    ssl_nginx_server_config = 'include nginx.conf.d/ssl-staging.conf;',

    session_name = '__Host-snapsession-staging',
})
